# Site Settings
lang: en
title: Rob Vleeshouwers
tagline: Welcome to my web site
email: robvlees@gmail.com
description: >
  Welcome to my Personal web site
baseurl:
url: "https://www.vleeshouwers.ch"
permalink: pretty
favicon: /img/favicon-32x32.png
gh_sponsor: 
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr
#force_theme: light

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: robvlees


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass
  # load_paths: 
    # - node_modules

#google_analytics: UA-code-here
cookie_policy: /cookie-policy/

defaults:
  -
    scope:
      path: ""
    values:
      image: /img/Web-hero-background_01.jpg
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "R. Vleeshouwers"
      author_image: /img/me.jpg
      layout: post
      image: /img/Logo.png
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://picsum.photos/id/16/800/600
    show_sidebar: false

google:
      tag_manager:
        container_id: G-703WPBYY61

jekyll-seo-tag:
      defaults:
        title: "Rob's web site"
        description: "Welcome to my web site"
        image: "/img/logo.png"
        url: "{{ site.url }}"
        

facebook:
  publisher: https://www.facebook.com/rob.vleeshouwers
        
social:
  name: Rob Vleeshouwers
  linkedin: https://www.linkedin.com/in/vleeshouwers/
  facebook: https://www.facebook.com/rob.vleeshouwers
  github: https://github.com/robvlees
  vimeo: https://vimeo.com/user5783542
  